language: rust
sudo: false
rust:
  - 1.15.0
  - 1.22.0 # rand
  - 1.26.0 # has_i128
  - 1.31.0 # 2018!
  - 1.36.0 # alloc
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - ./ci/test_full.sh
matrix:
  include:
    - name: "Rust: stable-i686"
      rust: stable-i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-multilib
    # try a target that doesn't have std at all, but does have alloc
    - name: "no_std"
      rust: stable
      env: TARGET=thumbv6m-none-eabi
      before_script:
        - rustup target add $TARGET
      script:
        - cargo build --verbose --target $TARGET --no-default-features --features i128
    - name: "rustfmt"
      rust: 1.31.0
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - next
    - staging
    - trying
